<h3>Material - Metal - AÇO</h3>

<p>O aço é basicamente uma liga (mistura homogênea de dois ou mais componentes cujo pelo menos um é metal) de ferro com uma quantidade de carbono de até 2%. Entretanto, o aço pode ser composto também por outros elementos, como o manganês, silício e tungstênio.  </p>
<p>Aço é um tipo de metal com uma enorme versatilidade, podendo ser utilizado na fabricação de peças (parafusos, engrenagens, eixos, etc), ferramentas (serras, martelos, pás, etc) e estruturas (pontes, tanques e edifícios). Os diferentes destinos dados a esse material se dão por conta do baixo custo de obtenção, da grande ductilidade e tenacidade e principalmente à ampla variedade de propriedades obtidas por meio de pequenas alterações na composição química. </p>
<p>A produção do aço pode ser a partir do minério de ferro, por meio da queima do excesso de carbono presente no ferro de gusa (ferro com teor de carbono entre 3% e 4%), onde dentro de um forno em alta temperatura, a injeção de oxigênio controla a quantidade de carbono do ferro. Ou a partir da reciclagem, o processo de queima é o mesmo, porém a partir da fusão da sucata. </p>
<p>Para classificarmos um material, é preciso seguir alguns critérios, como cor ou peso. O aço não possui um critério único, por isso, constantemente nos deparamos com conceitos do tipo: aço ao carbono, aço para ferramentas, aço fundido e aço inoxidável. Isso porque alguns dos critérios utilizados para sua classificação são: a composição (carbono), a aplicação (para ferramenta), o processamento (fundido) e a propriedade (inoxidável).</p>
<p>Esses critérios estão interligados: o processamento e a composição determinam a microestrutura do material, que determina as propriedades, que por sua vez determina o campo de aplicação do material</p>
<p>Uma das classificações mais utilizadas na indústria é a que relaciona o teor de carbono, como representado na tabela:</p>


