<header class="fixed-top">
    <nav class="navbar navbar-expand-md navbar-dark">
        <img src="img/nome.png" width=200 height=90>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <img src="img/menu.png" width=30 height=30>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="nav navbar-nav ml-auto rounded" style="background-color: #e9e9e9;">
                <ul class="navbar-nav" style="margin:10px 0px 10px 30px;">
                    <li class="nav-item">
                        <a href="index.php" style="margin-right:30px;"> <img src="img/casa.png" width=25 height=25> </a>
                    </li>
                    <li class="nav-item">
                        <a href="materia.php" style="margin-right:30px;" class="button"> <img src="img/materia.png" width=20 height=20> Matéria </a>
                    </li>
                    <li class="nav-item">
                        <a href="videos.php" style="margin-right:30px;"> <img src="img/video.png" width=20 height=20> Vídeo aulas </a>
                    </li>
                    <li class="nav-item">
                        <a href="sites.php" style="margin-right:30px;"> <img src="img/www.png" width=20 height=20> Sites </a>
                    </li>
                    <li class="nav-item">
                        <a href="exercicios.php" style="margin-right:30px;"> <img src="img/exercicio.png" width=20 height=20> Exercícios </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
