<header class="fixed-top">
    <nav class="navbar navbar-expand-md navbar-dark">
        <a href="index.php"><img src="img/logo3.png" width=220 height=170 style="margin-top:-15px;"></a>
        <button style="margin-top:18px;" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <img src="img/menu.png" width=30 height=30>
        </button>
    </nav>
</header>
