<h2> Introdução </h2>

<p>De um modo geral, materiais são substâncias químicas simples ou compostas que dão ao homem a capacidade de construir o que chamamos de dispositivos, que por sua vez, são objetos construídos com uma determinada função.</p>
<p>Os materiais possuem ligação direta com o processo de desenvolvimento da humanidade, e com o passar do tempo, foram desenvolvendo funções cada vez mais específicas.</p>
<p>O que diferencia os materiais uns dos outros são suas propriedades químicas, sendo assim, são divididos em três grupos principais: polímeros, metais e cerâmicas, a união desses grupos deu origem ao grupo dos materiais compósitos, que hoje exibe grande importância tecnológica.</p>
<p>Para que sejam utilizados de maneira adequada, é preciso entender sua estrutura interna, o que facilita identificar seu comportamento em determinada tarefa. Por isso temos a área de conhecimento “Ciência e Engenharia dos materiais”, que é responsável pelo emprego de conceitos envolvendo composição química, arranjo atômico e processamento dos materiais com suas características e empregos. Essa área do conhecimento pode ser dividida em dois segmentos: o da ciência, caracterizado principalmente por revelar os conhecimentos básicos da estrutura interna dos materiais; e o da engenharia, baseado no emprego de conceitos fundamentais e na conversão dos mesmos em produtos finais.</p>


