<nav class="navbar navbar-expand-md navbar-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="nav navbar-nav ml-auto">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="materia.php"> <img src="materia.png" width=20 height=20> Matéria </a>
                </li>
            </ul>
        </div>
    </div>
</nav>






<!--<div class="menu">
    <center>
        <a href="index.php"> <img src="casa.png" width=25 height=25> </a>
        <a href="materia.php"> <img src="materia.png" width=20 height=20> Matéria </a>
        <a href="videos.php"> <img src="video.png" width=20 height=20> Vídeo aulas </a>
        <a href="sites.php"> <img src="www.png" width=25 height=25> Sites </a>
        <a href="exercicios.php"> <img src="exercicio.png" width=20 height=20> Exercícios </a>
    </center>
</div>-->